多发行构建

diff --git a/.github/workflows/release-build.yml b/.github/workflows/release-build.yml
--- a/.github/workflows/release-build.yml
+++ b/.github/workflows/release-build.yml
@@ -8,20 +8,44 @@ env:
 
 name: release-build
 jobs:
-  build-linux:
-    runs-on: ubuntu-latest
+  build:
+    strategy:
+      matrix:
+        os: [macos-latest, ubuntu-latest, windows-latest]
+    runs-on: ${{ matrix.os }}
     steps:
-      - name: '检查 GitHub Action'
+      - name: '签出仓库'
         uses: actions/checkout@v4
 
       - name: '检查 tag'
-        shell: bash
+        shell: ${{ matrix.os == 'ubuntu-latest' && 'bash' || (matrix.os == 'windows-latest' && 'pwsh' || 'bash') }}
         run: |
-          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
-          tag_name="${GITHUB_REF##*/}"
-          echo Tag $tag_name
-          git checkout $tag_name
-          echo "TAG_NAME=${tag_name}" >> $GITHUB_ENV
+          if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
+            git fetch --depth=1 origin +refs/tags/*:refs/tags/*
+            tag_name="${GITHUB_REF##*/}"
+            echo "Tag $tag_name"
+            git checkout $tag_name
+            echo "TAG_NAME=${tag_name}" >> $GITHUB_ENV
+          elif [ ${{ matrix.os }} == 'macos-latest' ]; then
+            git fetch --depth=1 origin +refs/tags/*:refs/tags/*
+            tag_name="${GITHUB_REF##*/}"
+            echo "Tag $tag_name"
+            git checkout $tag_name
+            echo "TAG_NAME=${tag_name}" >> $GITHUB_ENV
+          else
+            if (-not $env:GITHUB_REF) {
+              Write-Error "GITHUB_REF is not set."
+              exit 1
+            }
+            $tag_name = $env:GITHUB_REF.Split('/')[-1]
+            if (-not $tag_name) {
+              Write-Error "Tag name could not be extracted."
+              exit 1
+            }
+            Write-Output "Tag $tag_name"
+            git checkout $tag_name
+            echo "TAG_NAME=$tag_name" >> $env:GITHUB_ENV
+          fi
 
       - name: 初始化 Python ${{ env.PYTHON_VERSION }} 环境
         uses: actions/setup-python@v4
@@ -44,54 +68,6 @@ jobs:
         with:
           repo_token: ${{ secrets.GITHUB_TOKEN }}
           tag: ${{ env.TAG_NAME }}
-          file: build/main.bin
-          asset_name: DDNetToolBox-${{ runner.os }}-${{ env.TAG_NAME }}
+          file: ${{ matrix.os == 'ubuntu-latest' && 'build/main.bin' || (matrix.os == 'windows-latest' && 'build/main.exe' || 'build/main.bin') }}
+          asset_name: DDNetToolBox-${{ runner.os }}-${{ env.TAG_NAME }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
           prerelease: true
-
-  build-windows:
-    runs-on: windows-latest
-    environment: dev
-    steps:
-    - name: '检查 GitHub Action'
-      uses: actions/checkout@v4
-
-    - name: '检查 tag'
-      shell: pwsh
-      run: |
-        if (-not $env:GITHUB_REF) {
-          Write-Error "GITHUB_REF is not set."
-          exit 1
-        }
-        $tag_name = $env:GITHUB_REF.Split('/')[-1]
-        if (-not $tag_name) {
-          Write-Error "Tag name could not be extracted."
-          exit 1
-        }
-        Write-Output "Tag $tag_name"
-        git checkout $tag_name
-        echo "TAG_NAME=$tag_name" >> $env:GITHUB_ENV
-
-    - name: 初始化 Python ${{ env.PYTHON_VERSION }} 环境
-      uses: actions/setup-python@v4
-      with:
-        python-version: ${{ env.PYTHON_VERSION }}
-
-    - name: '使用 pip 安装依赖'
-      shell: bash
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
-
-    - name: '构建发行'
-      shell: bash
-      run: |
-        python setup.py build
-
-    - name: '上传发行'
-      uses: svenstaro/upload-release-action@v2
-      with:
-        repo_token: ${{ secrets.GITHUB_TOKEN }}
-        tag: ${{ env.TAG_NAME }}
-        file: build/main.exe
-        asset_name: DDNetToolBox-${{ runner.os }}-${{ env.TAG_NAME }}.exe
-        prerelease: true
